# Generated by Django 5.1.3 on 2024-11-20 16:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dots',
            fields=[
                ('dot_id', models.AutoField(primary_key=True, serialize=False)),
                ('dot_name', models.CharField(default='Dot', help_text="Dot's name", max_length=150)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('completed_at', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('dot_type', models.CharField(blank=True, choices=[('w', 'WRITE'), ('r', 'REWRITE'), ('s', 'SUMMARIZE')], default='w', help_text='Type of Dot', max_length=1, null=True)),
            ],
            options={
                'db_table': 'dots',
            },
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yearly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('content_rewrite', models.BooleanField(blank=True, default=False, null=True)),
                ('seo_optimization', models.BooleanField(blank=True, default=False, null=True)),
                ('keyword_suggestions', models.BooleanField(blank=True, default=False, null=True)),
                ('content_automation', models.BooleanField(blank=True, default=False, null=True)),
                ('target_audience_analysis', models.BooleanField(blank=True, default=False, null=True)),
                ('max_posts_per_month', models.IntegerField(blank=True, null=True)),
                ('ai_support_level', models.CharField(blank=True, choices=[('b', 'BASIC'), ('i', 'INTERMEDIATE'), ('a', 'ADVANCED'), ('e', 'ENTERPRISE')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'price_plan',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('role', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserPlanSubscriptions',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remaining_posts', models.IntegerField(blank=True, null=True)),
                ('renewal_date', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dot.priceplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dot.users')),
            ],
            options={
                'db_table': 'user_plan_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(default=datetime.datetime.now)),
                ('payment_status', models.CharField(blank=True, choices=[('c', 'COMPLETED'), ('p', 'PENDING'), ('f', 'FAILED')], max_length=1, null=True)),
                ('card_type', models.CharField(blank=True, choices=[('cc', 'CREDIT CARDS'), ('dc', 'DEBIT CARDS'), ('pc', 'PRE-PAID CARDS')], max_length=2, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dot.priceplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dot.users')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='DotUseHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('dot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dot.dots')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dot.users')),
            ],
            options={
                'db_table': 'dot_use_history',
            },
        ),
    ]
